### ISSUE TITLE
Add hsflowd 2.0.17-1 to OPX installer

### ISSUE THREAD

**Issue by jeffyin-dell** [open-switch/opx-onie-installer#20]
NTP: We've been asked to add the ntp package by default to the OPX installer (https://packages.debian.org/stretch/ntp)

hsflowd: InMon has given us permission to host the hsflowd 2.0.17-1 in our own package repo. Please build and install the hsflowd 2.0.17-1 Debian package for OPX and place it in the contrib repository, then include it in the OPX installer.

**Comment by heucke** [comment]
Is this a one-time publish for hsflowd? If so, we can definitely host it. If not (if you ever anticipate updating it), InMon needs to be hosting it, since they develop it.

Otherwise, we need to fork the repository and establish a development/release workflow.

**Comment by heucke** [comment]
Splitting out the NTP issue into #21 from the hsflowd issue since they are completely independent.

**Comment by jeffyin-dell** [comment]
(My bad on the NTP issue)
Yeah, it's a one-time publish for hsflowd. Don't need to fork the code.

**Comment by heucke** [comment]
I cloned the repository for hsflowd, but don't see any way to build for OPX on Stretch.

1. There are no build instructions in the README
2. `make` does not produce any packages
2. `make opx` and `make OPX` do not work
3. `./docker_build_on opx` uses Debian Jessie and OPX 2.2.0 to build
4. Our OPX build script does not work because the repository does not follow the Debian repository layout

**Comment by jeffyin-dell** [comment]
Neil from InMon says that he ran `docker pull opxhub/build` and then changed the `host-sflow/docker_build/opx/Dockerfile` to refer to `latest`.

**Comment by jeffyin-dell** [comment]
Also, the `make` command ought to be `make deb FEATURES=OPX` IIRC

**Comment by heucke** [comment]
Thanks for the info. I’ll wait for them to update the repo with the fixes.

**Comment by jeffyin-dell** [comment]
InMon says they have updated their repo with the latest.

However, OpenSwitch still needs to validate it in System Test. Please stand by.
