### ISSUE TITLE
Add ntp to installer

### ISSUE THREAD

**Issue by heucke** [open-switch/opx-onie-installer#21]
NTP: We've been asked to add the ntp package by default to the OPX installer (packages.debian.org/stretch/ntp)

**Comment by heucke** [comment]
@jeff-yin 

https://github.com/open-switch/opx-onie-installer/blob/master/release_bp/opx_debian_base_stretch.xml#L22

ntp is already in the installer...

**Comment by jeffyin-dell** [comment]
Thanks, sorry about that. I was looking at an old commit.
