### ISSUE TITLE
why are there 2 OPX options when booting switch 

### ISSUE THREAD

**Issue by jimmymagemtek** [open-switch/opx-onie-installer#35]
Hi 
No sure if this is the right place to post the question, but I found there are two options of OPX when booting switch. The switch info is as below,

OS_NAME="OPX"
OS_VERSION="2.1.0"
PLATFORM="AS7512-32X"
ARCHITECTURE="x86_64"
INTERNAL_BUILD_ID="OpenSwitch blueprint for Cavium 1.0.0"
BUILD_VERSION="2.1.0.1"
BUILD_DATE="2017-11-17T15:01:29+0000"
INSTALL_DATE="2001-01-01T00:22:07+0000"
SYSTEM_UPTIME= 14 minutes
SYSTEM_STATE= degraded
UPGRADED_PACKAGES=no
ALTERED_PACKAGES=no

Why are there OPX-SYSROOT1  & OPX-SYSROOT2 ?
Thanks.
Jimmy

**Comment by jeffyin-dell** [comment]
Hi @jimmymagemtek, these two OPX instances are partitioned separately. Each of them have separate file systems, so you can work with one and switch to the other if the first one gets corrupted or changed undesirably.
